<!--
 * @Author: 27
 * @LastEditors: 27
 * @Date: 2020-04-02 00:04:11
 * @LastEditTime: 2020-04-02 00:04:11
 * @FilePath: /Coding-Daily/content/Python_Generate/python语言总结回顾/协程（流畅的python学习）/协程学习.md
 * @description: type some description
 -->
## 16.1 生成器如何进化成协程
`yield`关键字可以在表达式中使用，而且生成器 API 中增加了`.send(value)`方法。
生成器的调用 方可以使用`.send(...)`方法发送数据，发送的数据会成为生成器函数中`yield`表达式的值。
因此，生成器可以作为协程使用。

*协程是指一个过程，这个过程与调用方协作，产出由调用方提供的值。*

除了`.send(...)`方法，PEP 342 还添加了`.throw(...)`和`.close()`方法:
前者的作用是让调用方抛出异常，在生成器中处理;后者的作用是终止生成器。

**PEP 380** 对生成器函数的句法做了两处改动，以便更好地作为协程使用。
- 现在，生成器可以返回一个值;以前，如果在生成器中给`return`语句提供值，会抛出`SyntaxError`异常。
- 新引入了`yield from`句法，使用它可以把复杂的生成器重构成小型的嵌套生成器，省去了之前把生成器的工作委托给子生成器所需的大量样板代码。

## 16.2 用作协程的生成器的基本行为
```
def simple_coroutine():  # 协程使用生成器函数定义:定义体中有 yield 关键字。
    print('-> coroutine started')
    x = yield  # 如果协程只从客户那里接收数据，那么产出的值是None，这个值是隐式指定的，因为yield关键字右边没有表达式
    print('-> coroutine received:', x)


my_coro = simple_coroutine()  # 调用函数得到生成器对象
print(my_coro)  # <generator object simple_coroutine at 0x1012956d0>
next(my_coro)   # 因为生成器还没启动，没在yield处暂停，所以一开始无法发送数据。
my_coro.send(42)    # 调用这个方法后，协程定义体中的yield会计算出42，现在，协程会恢复，一直运行到下一个yield表达式，或者终止。
# 然后控制权流动到协程定义体的末尾，导致协程生成器向往常一样抛出StopIteration异常。
```
输出：
```
<generator object simple_coroutine at 0x10a1af6d0>
-> coroutine started
-> coroutine received: 42
Traceback (most recent call last):
  File "/Users/fzk27/fzk27/Coding-Daily/content/Python_Generate/python语言总结回顾/协程（流畅的python学习）/16-2.py", line 16, in <module>
    my_coro.send(42)    # 调用这个方法后，协程定义体中的yield会计算出42，现在，协程会恢复，一直运行到下一个yield表达式，或者终止。
StopIteration
```
顺序可能有点儿不太一样，比如类似这样：
```
Traceback (most recent call last):
<generator object simple_coroutine at 0x10a1af6d0>
  File "/Users/fzk27/fzk27/Coding-Daily/content/Python_Generate/python语言总结回顾/协程（流畅的python学习）/16-2.py", line 16, in <module>
-> coroutine started
-> coroutine received: 42
    my_coro.send(42)    # 调用这个方法后，协程定义体中的yield会计算出42，现在，协程会恢复，一直运行到下一个yield表达式，或者终止。
StopIteration
```
协程可以身处四个状态中的一个。当前状态可以使用 inspect.getgeneratorstate(...) 函数确定，该函数会返回下述字 符串中的一个。
- 'GEN_CREATED'，等待开始执行。
- 'GEN_RUNNING'，解释器正在执行。
>只有在多线程应用中才能看到这个状态。此外，生成器对象在自己身上调用getgeneratorstate 函数也行，不过这样做没什么用。

- 'GEN_SUSPENDED'，在 yield 表达式处暂停。 
- 'GEN_CLOSED'，执行结束。

因为`send`方法的参数会成为暂停的`yield`表达式的值，所以，仅当协程处于暂停状态时才能调用`send`方法**传值**，例如`my_coro.send(42)`。
不过，如果协程还没激活(即状态是'GEN_CREATED')，情况就不同了。
因此，始终要调用`next(my_coro)`激活协程——也可以调用`my_coro.send(None)`，效果一样。

如果创建协程对象后立即把 None 之外的值发给它，会出现下述错误:
```
>>> my_coro = simple_coroutine() 
>>> my_coro.send(1729)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
TypeError: can't send non-None value to a just-started generator
```
不能把非空的值传给刚建立好的生成器。

最先调用`next(my_coro)`函数这一步通常称为“预激”(prime)协程，
(即，让协程向前执行到第一个 yield 表达式，准备好作为活跃的协程使用)。

[上述示例源代码 ------> simple_coroutine](./16-2.py)

再来个产出两个值的协程：
```
def simple_coro2(a):
    print("-> Started: a =", a)
    b = yield a
    print("-> Received: b =", b)
    c = yield a + b
    print("-> Received: c =", c)

my_coro2 = simple_coro2(14)
from inspect import getgeneratorstate
print(getgeneratorstate(my_coro2))      # 处于GEN_CREATED状态，协程未启动
print(next(my_coro2))     # 预激协程，执行到第一个yield表达式，打印 -> Started: a = 14，然后产出a值，并且暂停等待为b赋值
print(getgeneratorstate(my_coro2))  # 处于GEN_SUSPENDED状态，即协程在yield表达式处暂停
print(my_coro2.send(28))        # 把数字28发给协程，计算yield表达式，得到28，然后赋值给b，打印 -> Received: b = 28消息，产出a+b的值42，然后协程暂停，等待为c赋值
try:
    print(my_coro2.send(99))    # 把数字99发给协程，计算yield表达式，得到99，然后赋值给c，打印 -> Received: c = 99消息，然后协程终止，产生StopIteration异常被texcept捕捉
except StopIteration as e:
    print("StopIteration!!!")   # 捕捉到StopIteration异常。
finally:
    print(getgeneratorstate(my_coro2))  # 可以清晰的看到抛出StopIteration后协程处于GEN_CLOSED状态（即协程执行结束）
```
输出为：
```
GEN_CREATED

-> Started: a = 14
14
GEN_SUSPENDED

-> Received: b = 28
42

-> Received: c = 99
StopIteration!!!

GEN_CLOSED
```
关键点是，协程在yield关键字所在的位置暂停执行。

也就是在赋值语句中，= 右边的代码在赋值前（send进值之前，排除掉函数传进参数的情况）执行，
因此对于`b = yield a`这行代码来说，等到客户端代码再激活协程时才会设定b的值。

这种行为要花点时间才能习惯，不过一定要理解，这样才能弄懂异步编程中yield的作用。

simple_coro2协程的执行过程分为三个阶段，如图：
![simple_coro2协程的过程](./img/协程16-2.png)
1. 调用`next(my_coro2)`，打印第一个消息，然后执行`yield a`，产出数字14。
2. 调用`my_coro2.send(28)`，把28赋值给b，打印第二个消息，然后执行`yield a+b`，产出数字42
3. 调用`my_coro2.send(99)`，把99赋值给c，打印第三个消息，协程遇见StopIteration，终止。
> 各个阶段都在yield表达式处结束，而下一个阶段都从那一行代码开始，然后再把yield表达式的值赋给变量。

[上述示例源代码 ------> simple_coro2](./16-2.py)


## 16.3 示例：使用协程计算移动平均值
之前讨论闭包时，我们分析了如何使用对象计算移动平均值:
- [示例 7-5](../装饰器和闭包（流畅的python学习）/7-5.py) 定义的是一个简单的类;
- [示例 7-6](../装饰器和闭包（流畅的python学习）/7-6.py) 定义的是一个高阶函数，用于生成一个闭包，在多次调用之间跟踪 total 和 count 变量的值。

下面示例展示如何使用协程实现相同的功能，定义一个计算移动平均值的协程
```
def averager():
    total = 0.0
    count = 0
    average = None
    while True:     # 这个无限循环表明，只要调用方不断把值发给这个协程，它就会一直接收值，然后生成结果。仅当调用方在协程上调用 .close() 方法，或者没有对协程的引用而被垃圾回收程序回收时，这个协程才会终止。
        term = yield average    # 这里的 yield 表达式用于暂停执行协程，把结果发给调用方;还用于接收调用方后面发给协程的值，恢复无限循环。
        total += term
        count += 1
        average = total/count

coro_avg = averager()   # 创建协程对象
print(next(coro_avg))   # 调用 next 函数，预激协程。
print(coro_avg.send(10))    # 计算移动平均值:多次调用 .send(...) 方法，产出当前的平均值。
print(coro_avg.send(30))
print(coro_avg.send(5))
```
输出：
```
None
10.0
20.0
15.0
```
[上述示例源代码 ------> averager](./16-3.py)

使用协程的好处是，total 和 count 声明为局部变量即可，无需使用实例属性或闭包在多次调用之间保持上下文。
在上述使用示例中，调用 next(coro_avg) 函数后，协程会向前执行到 yield 表达式，产出 average 变量的初始值——None。

此时，协程在 yield 表达式处暂停，等到调用方发送值。coro_avg.send(10) 那一行发送一个值，激活协程，把发送的值赋给 term，
并更新 total、count 和 average 三个变量的值，然后开始 while 循环的下一次迭代，产出 average 变量的值，等待下一次为 term 变量赋值。
细心的读者可能迫切地想知道如何终止执行 averager 实例(如 coro_avg)，因为定义体中有个无限循环。

讨论如何终止协程之前，我们要先谈谈如何启动协程。使用协程之前必须预激，可是这一步容易忘记。
为了避免忘记，可以在协程上使用一个特殊的装饰器。接下来介绍这样一个装饰器。

## 16.4 预激协程的装饰器
如果不预激，那么协程没什么用。调用 my_coro.send(x) 之前，记住一定要调用 next(my_coro)。
为了简化协程的用法，有时会使用一个预激装饰器。下面示例中的 coroutine 装饰器是一例。

实现一个预激协程的装饰器：
```
from functools import wraps

def coroutine(func):
    """装饰器:向前执行到第一个`yield`表达式，预激`func`"""
    @wraps(func)
    def primer(*args, **kwargs):  # 把被装饰的生成器函数替换成这里的 primer 函数;调用 primer 函数时，返回预激后的生成器。
        gen = func(*args, **kwargs)  #  调用被装饰的函数，获取生成器对象。
        next(gen)  # 预激生成器。
        return gen  # 返回生成器。
    return primer
```
使用示例中定义的 @coroutine 装饰器定义并测试计算移动平均值的协程:
```
@coroutine
def averager():
    total = 0.0
    count = 0
    average = None
    while True:  # 这个无限循环表明，只要调用方不断把值发给这个协程，它就会一直接收值，然后生成结果。仅当调用方在协程上调用 .close() 方法，或者没有对协程的引用而被垃圾回收程序回收时，这个协程才会终止。
        term = yield average  # 这里的 yield 表达式用于暂停执行协程，把结果发给调用方;还用于接收调用方后面发给协程的值，恢复无限循环。
        total += term
        count += 1
        average = total / count
coro_avg = averager() # 调用 averager() 函数创建一个生成器对象，在 coroutine 装饰器的 primer 函数中已经预激了这个生成器。
from inspect import getgeneratorstate
print(getgeneratorstate(coro_avg))  #  getgeneratorstate 函数指明，处于 GEN_SUSPENDED 状态，因此这个协程已经准备好，可以接收值了。
print(coro_avg.send(10))    # 可以立即开始把值发给 coro_avg——这正是 coroutine 装饰器的目的。
print(coro_avg.send(20))
print(coro_avg.send(15))
```
输出：
```
GEN_SUSPENDED
10.0
15.0
15.0
```
[上述示例源代码 ------> coroutine](./16-4.py)

很多框架都提供了处理协程的特殊装饰器，不过不是所有装饰器都用于预激协程，有些会提供其他服务，例如勾入事件循环。
比如说，异步网络库 Tornado 提供了 tornado.gen 装饰器。

使用 yield from 句法调用协程时，会自动预激，因此与我们示例中的 @coroutine 等装饰器不兼容。
Python 3.4 标准库里的 asyncio.coroutine 装饰器不会预激协程，因此能兼容 yield from 句法。

接下来探讨协程的重要特性——用于终止协程，以及在协程中抛出异常的方法。

## 16.5 终止协程和异常处理
协程中未处理的异常会向上冒泡，传给 next 函数或 send 方法的调用方(即触发协程的对象)。
下面示例举例说明如何使用之前示例中由装饰器定义的 averager 协程。

未处理的异常会导致协程终止：
```
coro_avg = averager()
print(coro_avg.send(40))
print(coro_avg.send(50))
try:
    print(coro_avg.send("spam"))   # 发送的值不是数字，导致协程内部有异常抛出。
except Exception as e:
    print(e)
finally:
    print(coro_avg.send(60))       # 由于在协程内没有处理异常，协程会终止。如果试图重新激活协程，会抛出 StopIteration 异常。
```
输出：
```
40.0
45.0
unsupported operand type(s) for +=: 'float' and 'str'
Traceback (most recent call last):
  File "/Users/fzk27/fzk27/Coding-Daily/content/Python_Generate/python语言总结回顾/协程（流畅的python学习）/16-5.py", line 35, in <module>
    print(coro_avg.send(60))
StopIteration
```
不加try，传字符串的时候是这样的：
```
Traceback (most recent call last):
...
TypeError: unsupported operand type(s) for +=: 'float' and 'str'
```
出错的原因是，发送给协程的 'spam' 值不能加到 total 变量上。

[上述示例源代码 ------> 协程异常情况](./16-5.py)

上面示例暗示了终止协程的一种方式:发送某个哨符值，让协程退出。

内置的 None 和 Ellipsis 等常量经常用作哨符值。Ellipsis 的优点是，数据流中不太常有这个值。
我还见过有人把 StopIteration 类(类本身，而不是实例，也不抛出)作为哨符值;也就是说，是像这样使用的:my_coro.send(StopIteration)。

从 Python 2.5 开始，客户代码可以在生成器对象上调用两个方法，显式地把异常发给协程。
这两个方法是 throw 和 close。

generator.throw(exc_type[, exc_value[, traceback]])

致使生成器在暂停的 yield 表达式处抛出指定的异常。
如果生成器处理了抛出的异常，代码会向前执行到下一个 yield 表达式，而产出的值会成为调用 generator.throw 方法得到的返回值。
如果生成器没有处理抛出的异常，异常会向上冒泡，传到调用方的上下文中。

generator.close()

致使生成器在暂停的 yield 表达式处抛出 GeneratorExit 异常。 
如果生成器没有处理这个异常，或者抛出了 StopIteration 异常(通常是指运行到结尾)，调用方不会报错。
如果收到 GeneratorExit 异常，生成器一定不能产出值，否则解释器会抛出 RuntimeError 异常。 
生成器抛出的其他异常会向上冒泡，传给调用方。

生成器对象方法的官方文档深藏在 Python 语言参考手册中， 参见
[“6.2.9.1.Generator-iterator methods”](https://docs.python.org/3/reference/expressions.html#generator-iterator-methods)。

下面举例说明如何使用 close 和 throw 方法控制协程。学习在协程中处理异常的测试代码:
```

```




